version: 2

models:
  - name: customers
    description: "Final customers table with order history and metrics"
    columns:
      - name: customer_id
        description: "The primary key for this table - unique customer identifier"
        data_tests:
          - unique
          - not_null
      
      - name: first_name
        description: "Customer's first name"
        data_tests:
          - not_null
      
      - name: last_name
        description: "Customer's last name"
        data_tests:
          - not_null
      
      - name: first_order
        description: "Date of customer's first order"
      
      - name: most_recent_order
        description: "Date of customer's most recent order"

      
      - name: number_of_orders
        description: "Total number of orders placed by the customer"

      
      - name: customer_orders
        description: "Total number of orders (same as number_of_orders, with null handling)"

